name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    name: Build and test (${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        arch: [ x64, arm64 ]
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-22.04-arm64' || 'ubuntu-latest' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential cmake valgrind

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBZM_BUILD_TESTS=ON

      - name: Build
        run: cmake --build build -j

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

      - name: Memcheck (Valgrind)
        run: cmake --build build --target memcheck

      - name: Upload test log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ctest-logs-${{ matrix.arch }}
          path: |
            build/Testing/Temporary/LastTest.log
            build/Testing/**/MemoryChecker.*.log

